### PR TITLE
add define to use custom snprintf

### PR DESCRIPTION
**Pull request by mgiaco**
This works for me with gnu arm gcc  6.2.0

### CODE REVIEW

**Comment by mgiaco** [comment]
I try to encapsulate first then I will try to add some defines to use a custom snprintf, snprintf_s or sprintf.

**Comment by mgiaco** [comment]
So that could maybe be a solution. I use it that way in my zf_log_config.h

```C
#define ZF_LOG_USE_CUSTOM_FORMATTING_FUNCTIONS
#define ZF_LOG_OPTIMIZE_SIZE
#include "printf.h"
#ifdef ZF_LOG_OPTIMIZE_SIZE
#define ZF_LOG_SNPRINTF snprintf
#endif
#define ZF_LOG_VSNPRINTF snprintf
```

**Comment by wonder-mice** [comment]
Sorry for long delay, have too much other thing going on. I appreciate you work on that, I'll try to think through it as soon as will get some spare time.

**Comment by mgiaco** [comment]
No problem I can live with my fork.

**Comment by mgiaco** [comment]
Hi,

Any news here?

**Comment by mgiaco** [comment]
@wonder-mice 
Are you still working on that project?

**Comment by wonder-mice** [comment]
Yes.

**Comment by wonder-mice** [comment]
Pushed `zf_log_config.h` part to master.

**Comment by wonder-mice** [comment]
What is the use case for custom snprintf?

**Comment by wonder-mice** [comment]
Ah, I see why (you are using custom printf library). Thing is that various printf implementation have different edge-case behavior... Just providing a printf-like functions doesn't look like excellent override point...

**Comment by mgiaco** [comment]
Okay so do you have any better idea? I really like ZF_LOG but i need it on a cortex m3 and cortex m4 embedded device. For printf i use https://github.com/mpaland/printf which seems to be very good.

**Comment by wonder-mice** [comment]
No, I don't have a better idea unfortunately. Just pushed a changed based on your proposal. Let me know how it works for you.

**Pull request closed without merging**
