### PR TITLE
Use __attribute__((format)) when available for _ZF_LOG_PRINTFLIKE()

### PR DESCRIPTION
**Pull request by eepp**

### CODE REVIEW

**Comment by wonder-mice** [comment]
LGTM, let's wait form CI checks to complete.

**Comment by eepp** [comment]
```

/Users/travis/build/wonder-mice/zf_log/examples/hello.c:19:56: error: format specifies type 'void *' but the argument has type 'const char *' [-Werror,-Wformat-pedantic]
        ZF_LOGW_MEM(data, sizeof(data), "Lorem ipsum at %p:", data);
                                                        ~~    ^~~~
                                                        %s
/Users/travis/build/wonder-mice/zf_log/zf_log/zf_log.h:858:56: note: expanded from macro 'ZF_LOGW_MEM'
                        ZF_LOG_WRITE_MEM(ZF_LOG_WARN, _ZF_LOG_TAG, d, d_sz, __VA_ARGS__)
                                                                            ^~~~~~~~~~~
/Users/travis/build/wonder-mice/zf_log/zf_log/zf_log.h:760:43: note: expanded from macro 'ZF_LOG_WRITE_MEM'
                                        _zf_log_write_mem(lvl, tag, d, d_sz, __VA_ARGS__); \
                                                                             ^~~~~~~~~~~
1 error generated.
```

Oops! Want to me to fix those (cast to `void *`, etc.) also?

**Comment by wonder-mice** [comment]
That would be highly appreciated!

**Comment by wonder-mice** [comment]
Thanks!

**Pull request merged**
