### PR TITLE
fix __func__ because the changes do not build on gcc and windows

### PR DESCRIPTION
**Pull request by mgiaco**
I added linux because I do not know how I can add windows in the build via ci

### CODE REVIEW

**Comment by wonder-mice** [comment]
travis doesn't support windows. appveyor is for that. Could you please describe why you added `&& !defined(__GNUC__)`? With what platform/compiler version it fails to build with?

**Comment by wonder-mice** [comment]
And do I understand correctly, that `__func__` does NOT work for you, but you have `___FUNCTION__`?

**Comment by wonder-mice** [comment]
Merged in manually: https://github.com/wonder-mice/zf_log/commit/e4ba99355fe951cf3763c796aa711a51079019af

**Comment by mgiaco** [comment]
No __func__ dose work for me. The problem is __FUNCTION__. 
The ifdef is for WIN32 and WIN64 okay thats fine but that works for Visual Studio but not for GCC. 6.x

**Comment by wonder-mice** [comment]
That was my last guess when I merged it in, cool.

**Pull request closed without merging**
