### PR TITLE
add defines to change the contex output

### PR DESCRIPTION
**Pull request by mgiaco**
Hello,

I added some new #defines to change the context content. Maybe someone also need this.

cheers
mathias

### CODE REVIEW

**Comment by wonder-mice** [comment]
Thanks, looks good. Though I don't see any arm specific code in that patch. How your patch helps with that? Do you want to modify library code locally for specific project?

**Comment by mgiaco** [comment]
After discussing with you I thought I will not use any embedded CPU dependent defines if possible. So implemented this function.

```C
int _gettimeofday( struct timeval *tv, void *tzvp )
{
	(void)tzvp;
    uint64_t now = get_system_tick()*1000; // get_system_tick() delivers the current up time in msec.
    tv->tv_sec = div_u64_by_1000000(now);
    tv->tv_usec = now - (tv->tv_sec * 1000000U);
    return 0;
}
`
Very important for me was do disable the Time and PID stuff via defines.

**Comment by mgiaco** [comment]
So there is something wrong with the __func__ define on Visual Studio as I found out. So I do not have any Visual Studio installed do you think this should be fix the problem if I add this in the header file?

```C
#ifdef _MSC_VER
#define __func__ __FUNCTION__
#endif
```

**Comment by biosmooth** [comment]
@mgiaco I had the same issue. After the discussion with @wonder-mice I implemented the fix in [this commit](https://github.com/biosmooth/zf_log/commit/310041e1591245b374ba1764da7330db28ab011f)

**Comment by mgiaco** [comment]
Okay thanks .. so you also do not need PID an TID as a can see. Are there any reasons why you don't create a pull request for the __func__ problem? For PID and TID. The YEAR problem could be fixed in the same way I fixed the PID, TID and TIME i think. 

@wonder-mice  I think the __FUNCTION__ problem should be fixed because gcc > 5.0 does not support that any more as I found out here [https://gcc.gnu.org/gcc-5/porting_to.html](url). Should I go with the solution of @biosmooth or do you have any other suggestions how to solve that.

**Comment by biosmooth** [comment]
@mgiaco, yes I didn't create a pull request due to PID,TID and YEAR. I like the way you customized PID, TID and TIME. I will think about something similar.

@mgiaco [pull request](https://github.com/wonder-mice/zf_log/pull/15) created.

**Comment by wonder-mice** [comment]
Thanks for contributing to the project, I'll take a close look on the patches and merge them once I have a bit more time (later this week).

**Comment by wonder-mice** [comment]
Btw, with your version of MSVS, can you compile the following code?

```c
#include <stdio.h>

#define ZF_LOG_CONTEXT_FORMAT(_, T, YEAR, MONTH, DAY, HOUR, MINUTE, SECOND, MILLISECOND, PID, TID, LEVEL) \
    _(MONTH) _(T("-")) _(DAY) _(T(" ")) _(HOUR) _(T(":")) _(MINUTE) _(T(":")) _(SECOND) _(T(".")) _(MILLISECOND) _(T(" ")) _(PID) _(T(" ")) _(LEVEL) _(T(" "))

#define AS_IS(what) what
#define NOOP(what)

#define HAS_MONTH (0 ZF_LOG_CONTEXT_FORMAT(AS_IS, NOOP,,||1,,,,,,,,))

void foo()
{
#if !HAS_MONTH
#error Should have a month
#endif
    fprintf(stderr, "%s\n",
            ZF_LOG_CONTEXT_FORMAT(AS_IS, AS_IS,
                                  "year:%s;", "month:%s;", "day:%s;",
                                  "hour:%s;", "minute:%s;", "second:%s;", "millisecond:%s;",
                                  "pid:%i;", "tid:%i;", "level:%c;"));
}
```

**Comment by wonder-mice** [comment]
Well, it seems to work. Next, I will try to introduce `ZF_LOG_CONTEXT_FORMAT` compile time option that will define what goes into `context` part of log line. It will look something like that:
```c
#define ZF_LOG_CONTEXT_FORMAT(T, YEAR, MONTH, DAY, HOUR, MINUTE, SECOND, MILLISECOND, PID, TID, LEVEL) \
    (MONTH, T("-"), DAY, T(" "), HOUR, T(":"), MINUTE, T(":"), SECOND, T("."), MILLISECOND, T(" "), PID, T(" "), TID, T(" "), LEVEL, T(" "))
```

So, if you want year, but don't want pid and tid, you will define it to:
```c
#define ZF_LOG_CONTEXT_FORMAT(T, YEAR, MONTH, DAY, HOUR, MINUTE, SECOND, MILLISECOND, PID, TID, LEVEL) \
    (YEAR, T("-"), MONTH, T("-"), DAY, T(" "), HOUR, T(":"), MINUTE, T(":"), SECOND, T("."), MILLISECOND, T(" "), LEVEL, T(" "))
```

All this preprocessor magic is required to preserve existing speed and size optimizations.

**Comment by wonder-mice** [comment]
Though would like to think more how custom fields, like systick, can be added.

**Comment by mgiaco** [comment]
Hello - yes it works for me. I just checked you code.

I get this output when i call foo()

```C
month:%s;-day:%s; hour:%s;:minute:%s;:second:%s;.millisecond:%s; pid:%i; level:%c; 
```

**Comment by wonder-mice** [comment]
Thanks for checking.
Also would be nice if you could check that you can build (just build) with tests (no need to run them) this branch:
https://github.com/wonder-mice/zf_log/tree/line-format

CI tools (win,lin,mac) show that it's fine, but looks like your compiler is somehow different from what I have.

**Comment by mgiaco** [comment]
okay i will check that. I use https://msys2.github.io/ but I can check also with this compiler http://tdm-gcc.tdragon.net/ - and I also check it with gnu arm gcc. I will report later.

**Comment by mgiaco** [comment]
Hello yes now I can build that but I need to change the latest pull request - sorry I do not check that before. I thought the fix also works for me.  But it dosn´t. So I have to change this:

```C
#if defined(_WIN32) || defined(_WIN64)
#ifdef _MSC_VER
    #define _ZF_LOG_FUNCTION __FUNCTION__
#else
	#define _ZF_LOG_FUNCTION __func__
#endif
#else
	#define _ZF_LOG_FUNCTION __func__
#endif
``` 

This function name stuff is really a pain. But I think that should work also for you now. I found this information here [http://stackoverflow.com/questions/4164315/how-to-check-if-pretty-function-can-be-used
](url)
But why do you need __FUNCTION__? gcc is fine with __func__ since c99 and visual studio should also work with __func__.

**Comment by mgiaco** [comment]
So I thinks only use __func__ works fine for everyone.

**Comment by biosmooth** [comment]
@mgiaco  using only ```__func__``` does not work fine for visual studio 2012 ([details](http://stackoverflow.com/questions/15126387/func-c11-functions-local-predefined-variable-wont-compile))

**Comment by mgiaco** [comment]
@biosmooth okay but then the suggestion above should work. Or it is possible to add some more specific defines

```C
#if (_MSC_VER == 1500)
   // ... Do VC9/Visual Studio 2008 specific stuff
#elif (_MSC_VER == 1600)
   // ... Do VC10/Visual Studio 2010 specific stuff
#elif (_MSC_VER == 1700)
   // ... Do VC11/Visual Studio 2012 specific stuff
#endif
```

**Comment by wonder-mice** [comment]
Did you look on my latest commit(s) to master? Problem should be fixed there (or so I think).

**Comment by wonder-mice** [comment]
@mgiaco @biosmooth Checkout this branch:
https://github.com/wonder-mice/zf_log/tree/line-format

I added custom format specifications and default delimiters via following defines in zf_log.c:
* `ZF_LOG_MESSAGE_CTX_FORMAT`
* `ZF_LOG_MESSAGE_TAG_FORMAT`
* `ZF_LOG_MESSAGE_SRC_FORMAT`
* `ZF_LOG_DEF_DELIMITER`

It's not cleaned up yet, but seems like that what you need.

For example, to use custom function
```c
unsigned getticks();
```
in message context:
```c
#define ZF_LOG_MESSAGE_CTX_FORMAT \
    (F_UINT(5, getticks()), S(" "), LEVEL, S(ZF_LOG_DEF_DELIMITER))
```

You probably get some compilation warnings if you try that now, but I'll fix that soon.

**Comment by wonder-mice** [comment]
Pushed changes to the master branch.

**Comment by mgiaco** [comment]
Hello, sorry I was away from this topic. But today I came back and tried your latest commits but now I am not able to build the lib anymore.

I do not modify anything it was just a checkout and denn I use.

```shell
mkdir Debug
cd Debug
cmkae -G Ninja ..
ninja 
```

Output: 

```
E:\github_c\zf_log\zf_log\zf_log.c:1358:0: error: "_PP_NARGS" redefined

 #define _PP_NARGS(...) _PP_EXPAND(_PP_NARGS_N(__VA_ARGS__,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1))

 

E:\github_c\zf_log\zf_log\zf_log.c:335:0: note: this is the location of the previous definition

 #define _PP_NARGS(...) _PP_ID(_PP_NARGS_N(__VA_ARGS__,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0))

 

E:\github_c\zf_log\zf_log\zf_log.c:1365:0: error: "_PP_HEAD_" redefined

 #define _PP_HEAD_(...) _PP_EXPAND(_PP_HEAD__(__VA_ARGS__, ~))

 

E:\github_c\zf_log\zf_log\zf_log.c:342:0: note: this is the location of the previous definition

 #define _PP_HEAD_(...) _PP_ID(_PP_HEAD__(__VA_ARGS__, ~))
```

What compiler are you using.

**Comment by mgiaco** [comment]
Also Visual Studio 14 2015 compiler did not work.

```shell
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug Win32 ------
1>  Checking Build System
1>  CMake does not need to re-run because E:/github_c/zf_log/vs2015/CMakeFiles/generate.stamp is up-to-date.
1>  CMake does not need to re-run because E:/github_c/zf_log/vs2015/zf_log/CMakeFiles/generate.stamp is up-to-date.
2>------ Build started: Project: zf_log, Configuration: Debug Win32 ------
2>  Building Custom Rule E:/github_c/zf_log/zf_log/CMakeLists.txt
2>  CMake does not need to re-run because E:\github_c\zf_log\vs2015\zf_log\CMakeFiles\generate.stamp is up-to-date.
2>  zf_log.c
2>E:\github_c\zf_log\zf_log\zf_log.c(1358): error C2220: warning treated as error - no 'object' file generated
2>E:\github_c\zf_log\zf_log\zf_log.c(1358): warning C4005: '_PP_NARGS': macro redefinition
2>  E:\github_c\zf_log\zf_log\zf_log.c(335): note: see previous definition of '_PP_NARGS'
2>E:\github_c\zf_log\zf_log\zf_log.c(1365): warning C4005: '_PP_HEAD_': macro redefinition
2>  E:\github_c\zf_log\zf_log\zf_log.c(342): note: see previous definition of '_PP_HEAD_'
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by wonder-mice** [comment]
Maybe a merge conflict on your side? Latest zf_log.c has only 1346 lines. Can't see how you can get error on line 1365 or 1358. Also CI builds are fine.

**Comment by wonder-mice** [comment]
I assume this was resolved.

**Comment by mgiaco** [comment]
Ah yes sorry.

**Pull request closed without merging**
