### PR TITLE
Update .appveyor.yml

### PR DESCRIPTION
**Pull request by mgiaco**
try to add mingw

### CODE REVIEW

**Comment by mgiaco** [comment]
So I need to check how I can use a newer gcc for appveyor. But I am wondering why this error with memccpy happens.

**Comment by mgiaco** [comment]
Do you have any idea how to add a mingw to that project?

**Comment by wonder-mice** [comment]
So I assume you don't have this `memccpy` problem on your machine?

**Comment by wonder-mice** [comment]
Looks like we need mingw-64 for that to work. Or implement "memccpy", but not sure how to do it only for this half-assed system.

**Comment by wonder-mice** [comment]
See https://github.com/wonder-mice/zf_log/commit/e3ecea92f38d815dbafc92b58230b9c6f450d87d

**Pull request closed without merging**
